---
driver:
  name: ec2
  aws_ssh_key_id: awsplayground_ohio
  region: us-east-2
  availability_zone: b
  subnet_id: subnet-f113ac8b
  instance_type: t2.micro
  image_id: ami-03291866
  security_group_ids: ["sg-0cb8d1612fb977743"]
  retryable_tries: 120

provisioner:
  name: chef_zero


verifier:
  name: inspec

transport:
  ssh_key: /home/vagrant/workplace/aws_playground.pem

platforms:
  - name: RHEL-7.5

suites:
  - name: default
    run_list:
      - recipe[tomcat_cookbook::install]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
